artifact_location: /Users/maicolrodrigues/Documents/Test/FIA/model_trained/mlflow/0
creation_time: 1725142393527
experiment_id: '0'
last_update_time: 1725142393527
lifecycle_stage: active
name: Default
